# NOTE: variables set here are considered to be CONSTANTS due to high precedence

srv_announcer_service_name: "{{ role_name }}"

srv_announcer_artifact_target_path: '/tmp/srv-announcer.tar.gz'
srv_announcer_bin_path: '/usr/local/bin/srv-announcer'
srv_announcer_configuration_path: '/usr/local/etc/srv-announcer'
srv_announcer_environment_variables_path: "{{ srv_announcer_configuration_path }}/credentials.env"
