galaxy_info:
  role_name: sft-server
  author: wireapp
  description: SFT server to be used with wire-server
  company: Wire Swiss GmbH
  license: AGPL

  min_ansible_version: 2.7
  github_branch: master

  platforms:
    - name: Ubuntu
      versions:
        - 18.04

  galaxy_tags:
    - SFT

dependencies:
  - name: cloudalchemy.node-exporter
    src: git+https://github.com/cloudalchemy/ansible-node-exporter
    version: 0.21.5
    vars:
      node_exporter_web_listen_address: "127.0.0.1:{{ sft_node_exporter_port }}"
    # NOTE: install but only invoke ...
    when: sft_metrics_enabled
