galaxy_info:
  role_name: sft-server
  author: wireapp
  description: SFT server to be used with wire-server
  company: Wire Swiss GmbH
  license: AGPL

  min_ansible_version: 2.7
  github_branch: master

  platforms:
    - name: Ubuntu
      versions:
        - 18.04

  galaxy_tags:
    - SFT
    - TURN

dependencies: []
