# NOTE: considered to be constants due to high precedence

SFT_ARTIFACT_TARGET_PATH: '/tmp/sft-artifact.tar.gz'
SFT_BIN_PATH: '/usr/local/bin/sftd'

# NOTE: currently hardcoded in source, but will soon be configurable
SFTD_SIGNALING_PORT: 8585
SFTD_METRICS_PORT: 49090

SFTD_USER: 'sft'
SFTD_GROUP: 'sft'



NGINX_CONF_PATH: '/etc/nginx/nginx.conf'
NGINX_CONF_DIR: '/etc/nginx/conf.d'
