# NOTE: variables set here are considered to be CONSTANTS due to high precedence

sft_artifact_target_path: '/tmp/sft-artifact.tar.gz'

sftd_bin_path: '/usr/local/bin/sftd'
# NOTE: currently hardcoded in source, but will soon be configurable
sftd_signaling_port: 1030
sftd_metrics_port: 1040

# NOTE: use the complete range of non-privileged ports
sftd_udp_port_range_start: 1024
sftd_udp_port_range_end: 65535

sftd_incoming_ip: '127.0.0.1'

# TODO: adjust calculation when/if an actual port range is defined. Also, see task 'allowing sft media ingress'
sftd_limit_nofile: "{{ 65536 - 1024 }}"

nginx_conf_dir: '/etc/nginx/conf.d'
nginx_dhparams_path: '/etc/ssl/nginx-dhparams.pem'

# NOTE: defaults to 1024 but since `ulimit -n` typically defaults to 1024 already and
#       the overall amount of connections includes all sorts of connections, the number
#       of open files must at least be be doubled
# DOCS: http://nginx.org/en/docs/ngx_core_module.html#worker_connections
# SRC:  https://stackoverflow.com/questions/37591784/nginx-worker-rlimit-nofile
nginx_worker_connections: 2048
nginx_rlimit_nofile: "{{ nginx_worker_connections * 2 }}"

# NOTE: defaulting to the amount of cores available on the system. Although, `sftd` itself
#       can only accept one request at a time. Which means, for this setup 2 workers/processes
#       should be fine: one for signaling and the other one for metrics
nginx_worker_processes: "{{ ansible_processor_vcpus if ansible_processor_vcpus <= 2 else 2 }}"

certbot_conf_path: '/etc/letsencrypt'
certbot_webroot_path: '/usr/share/nginx/certbot'

# NOTE: the following two paths are defined by certbot and not configurable
certbot_live_path: "{{ certbot_conf_path }}/live"
certbot_archive_path: "{{ certbot_conf_path }}/archive"

systemd_coredump_service_conf_dir: '/etc/systemd/coredump.conf.d'
systemd_nginx_service_conf_dir: '/etc/systemd/system/nginx.service.d'

sft_node_exporter_port: 9100
sft_node_exporter_listen: 127.0.0.1

sft_metrics_ca_path: /etc/nginx/ssl/certs/metrics-ca.crt

sft_nginx_certbot_port: '80'
sft_nginx_sft_port: '443'
sft_nginx_metrics_port: '8443'
