# NOTE: considered to be constants due to high precedence

SFT_ARTIFACT_TARGET_PATH: '/tmp/sft-artifact.tar.gz'
SFT_BIN_PATH: '/usr/local/bin/sftd'

# NOTE: currently hardcoded in source, but will soon be configurable
SFTD_SIGNALING_PORT: 8585
SFTD_METRICS_PORT: 49090

SFTD_USER: 'sft'
SFTD_GROUP: 'sft'



NGINX_CONF_PATH: '/etc/nginx/nginx.conf'
NGINX_CONF_DIR: '/etc/nginx/conf.d'
NGINX_DHPARAMS_PATH: '/etc/ssl/nginx-dhparams.pem'


CERTBOT_CONF_PATH: '/etc/letsencrypt'
CERTBOT_WEBROOT_PATH : '/usr/share/nginx/certbot'

# NOTE: the following two paths cannot really be configured for a certbot invocation
CERTBOT_LIVE_PATH: "{{ CERTBOT_CONF_PATH }}/live"
CERTBOT_ARCHIVE_PATH: "{{ CERTBOT_CONF_PATH }}/archive"

CERTBOT_CERT: "{{ CERTBOT_LIVE_PATH }}/{{ sft_fqdn }}/cert.pem"
CERTBOT_PRIVKEY: "{{ CERTBOT_LIVE_PATH }}/{{ sft_fqdn }}/privkey.pem"
CERTBOT_CHAIN: "{{ CERTBOT_LIVE_PATH }}/{{ sft_fqdn }}/chain.pem"
CERTBOT_FULLCHAIN: "{{ CERTBOT_LIVE_PATH }}/{{ sft_fqdn }}/fullchain.pem"
