dependency:
  name: galaxy
  options:
    # NOTE: even though 'sft_metrics_enabled' is set to false, 'converge' still throws complaining
    #       that note-exporter role is not installed. NO idea why, but if the scenario is made aware
    #       of the dependency, Molecule shuts up
    role-file: "${MOLECULE_SCENARIO_DIRECTORY}/../requirements.yml"
driver:
  name: hetznercloud
platforms:
  - name: "molecule-hetznercloud-${MOLECULE_SCENARIO_NAME}-${INSTANCE_UUID}"
    server_type: cx11
    image: ubuntu-18.04
    groups:
      - sft
verifier:
  name: ansible
provisioner:
  name: ansible
  playbooks:
    converge: ./converge.yml
    verify: ./verify.yml
    cleanup: ./../cleanup.yml
  inventory:
    links:
      group_vars: ./../inventory/group_vars
  # NOTE: inventory.group_vars wont work in conjunction with inventory.links
  ansible_args:
    - "--inventory=${MOLECULE_SCENARIO_DIRECTORY}/inventory.yml"
