# NOTE: since the template module does not provide a way to remove the rendered file,
#       this task will ensure that the configuration is reflected in the filesystem
#
- name: ensuring that the state of systemd service unit(es) is consistent
  file:
    dest: "/etc/systemd/system/{{ srv_announcer_service_name }}.{{ item.key }}.service"
    state: "{{ 'absent' if (item.value.deprecated | default(False)) else 'file' }}"
  loop: "{{ srv_announcer_srv_records | dict2items }}"
