- name: downloading {{ srv_announcer_service_name }} artifact by URL
  get_url:
    url: "{{ srv_announcer_artifact_file_url }}"
    checksum: "{{ srv_announcer_artifact_checksum }}"
    dest: "/tmp/srv-announcer.tar.gz"
  when:
    - srv_announcer_artifact_file_url is defined
    - srv_announcer_artifact_checksum is defined

- name: unpacking artifact
  unarchive:
    remote_src: yes
    src: "/tmp/srv-announcer.tar.gz"
    dest: '/tmp/'
    list_files: yes
  register: unpacked_srv_announcer

- name: copying {{ srv_announcer_service_name }} executable to right location
  copy:
    src: "/tmp/srv-announcer.tar.gz"
    remote_src: yes
    dest: "{{ srv_announcer_bin_path }}"
  register: binary_srv_announcer

- name: ensuring executable state
  file:
    path: "{{ srv_announcer_bin_path }}"
    state: 'file'
    mode: '755'
