- name: starting service(s) - {{ srv_announcer_service_name }}
  systemd:
    name: "{{ srv_announcer_service_name }}"
    enabled: yes
    state: >-
      {{
        'restarted' if
          (binary_srva is defined and binary_srva.changed)
          or
          (unit_srva is defined and unit_srva.changed)
          or
          (unit_conf_srva is defined and unit_conf_srva.changed)
          or
          (slice_srva is defined and slice_srva.changed)
        else 'started'
      }}
    daemon_reload: >-
      {{
        'yes' if
          (unit_srva is defined and unit_srva.changed)
          or
          (slice_srva is defined and slice_srva.changed)
        else 'no'
      }}
