- name: starting service(s) - {{ srv_announcer_service_name }}
  systemd:
    name: "{{ srv_announcer_service_name }}"
    enabled: yes
    state: >-
      {{
        'restarted' if
          (binary_srv_announcer is defined and binary_srv_announcer.changed)
          or
          (unit_srv_announcer is defined and unit_srv_announcer.changed)
          or
          (env_srv_announcer is defined and binary_srv_announcer.changed)
          or
          (slice_srv_announcer is defined and slice_srv_announcer.changed)
        else 'started'
      }}
    daemon_reload: >-
      {{
        'yes' if
          (unit_srv_announcer is defined and unit_srv_announcer.changed)
          or
          (slice_srv_announcer is defined and slice_srv_announcer.changed)
        else 'no'
      }}
