- name: Create CA private key
  openssl_privatekey:
    path: "{{ workspace.path }}/ca-key.pem"
- name: Upload CA private key
  aws_s3:
    bucket: "{{ sft_metrics_ca_private_key_s3_bucket }}"
    object: "{{ sft_metrics_ca_private_key_s3_path }}"
    src: "{{ workspace.path }}/ca-key.pem"
    mode: put
