- name: Create client key
  openssl_privatekey:
    path: "{{ workspace.path }}/client-key.pem"

- name: Upload client private key
  aws_s3:
    bucket: "{{ sft_metrics_client_s3_bucket }}"
    object: "{{ sft_metrics_client_private_key_s3_path }}"
    src: "{{ workspace.path }}/client-key.pem"
    mode: put
